---
version: 3
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: amazon.aws
images:
  base_image:
    name: registry.access.redhat.com/ubi9/python-312:latest@sha256:0c23550f08fb257342be41d1784af37906f9aee8aae8a577fb83e6b41d1d5e0c
